name: PHPCS check

on: push

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: fatfish/Navigation@master
        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
                enable_warnings: true
