name: PHPCS check

on: push

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: PHPCS check
          uses: fatfishdigital/Navigation@master
          with:
                enable_warnings: true
